// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: TokenService.proto

package Token_Service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TokenService_CreateToken_FullMethodName = "/TokenService/CreateToken"
	TokenService_DropToken_FullMethodName   = "/TokenService/DropToken"
	TokenService_WriteToken_FullMethodName  = "/TokenService/WriteToken"
	TokenService_ReadToken_FullMethodName   = "/TokenService/ReadToken"
)

// TokenServiceClient is the client API for TokenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenServiceClient interface {
	// Create a new token.
	CreateToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*CreateTokenResponse, error)
	// Drop an existing token.
	DropToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*DropTokenResponse, error)
	// Write data to a token.
	WriteToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*WriteTokenResponse, error)
	// Read data from a token.
	ReadToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*ReadTokenResponse, error)
}

type tokenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenServiceClient(cc grpc.ClientConnInterface) TokenServiceClient {
	return &tokenServiceClient{cc}
}

func (c *tokenServiceClient) CreateToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*CreateTokenResponse, error) {
	out := new(CreateTokenResponse)
	err := c.cc.Invoke(ctx, TokenService_CreateToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenServiceClient) DropToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*DropTokenResponse, error) {
	out := new(DropTokenResponse)
	err := c.cc.Invoke(ctx, TokenService_DropToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenServiceClient) WriteToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*WriteTokenResponse, error) {
	out := new(WriteTokenResponse)
	err := c.cc.Invoke(ctx, TokenService_WriteToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenServiceClient) ReadToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*ReadTokenResponse, error) {
	out := new(ReadTokenResponse)
	err := c.cc.Invoke(ctx, TokenService_ReadToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenServiceServer is the server API for TokenService service.
// All implementations must embed UnimplementedTokenServiceServer
// for forward compatibility
type TokenServiceServer interface {
	// Create a new token.
	CreateToken(context.Context, *Token) (*CreateTokenResponse, error)
	// Drop an existing token.
	DropToken(context.Context, *Token) (*DropTokenResponse, error)
	// Write data to a token.
	WriteToken(context.Context, *Token) (*WriteTokenResponse, error)
	// Read data from a token.
	ReadToken(context.Context, *Token) (*ReadTokenResponse, error)
	mustEmbedUnimplementedTokenServiceServer()
}

// UnimplementedTokenServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTokenServiceServer struct {
}

func (UnimplementedTokenServiceServer) CreateToken(context.Context, *Token) (*CreateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateToken not implemented")
}
func (UnimplementedTokenServiceServer) DropToken(context.Context, *Token) (*DropTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropToken not implemented")
}
func (UnimplementedTokenServiceServer) WriteToken(context.Context, *Token) (*WriteTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteToken not implemented")
}
func (UnimplementedTokenServiceServer) ReadToken(context.Context, *Token) (*ReadTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadToken not implemented")
}
func (UnimplementedTokenServiceServer) mustEmbedUnimplementedTokenServiceServer() {}

// UnsafeTokenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenServiceServer will
// result in compilation errors.
type UnsafeTokenServiceServer interface {
	mustEmbedUnimplementedTokenServiceServer()
}

func RegisterTokenServiceServer(s grpc.ServiceRegistrar, srv TokenServiceServer) {
	s.RegisterService(&TokenService_ServiceDesc, srv)
}

func _TokenService_CreateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServiceServer).CreateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenService_CreateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServiceServer).CreateToken(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenService_DropToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServiceServer).DropToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenService_DropToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServiceServer).DropToken(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenService_WriteToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServiceServer).WriteToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenService_WriteToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServiceServer).WriteToken(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenService_ReadToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServiceServer).ReadToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenService_ReadToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServiceServer).ReadToken(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenService_ServiceDesc is the grpc.ServiceDesc for TokenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TokenService",
	HandlerType: (*TokenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateToken",
			Handler:    _TokenService_CreateToken_Handler,
		},
		{
			MethodName: "DropToken",
			Handler:    _TokenService_DropToken_Handler,
		},
		{
			MethodName: "WriteToken",
			Handler:    _TokenService_WriteToken_Handler,
		},
		{
			MethodName: "ReadToken",
			Handler:    _TokenService_ReadToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "TokenService.proto",
}
